//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// ' For information on how interfaces are used in classes derived from Window,
// '   please see http://mauiweb.
namespace MOM10SP1_Install
{
    using System;
    using System.ComponentModel;
    using Maui.OS.WinControls;
    using Maui.OS;
    
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    public interface IMicrosoftOperationsManagerSetupRegistrationInformationDialogControls
    {
        StaticControl UsernameStaticControl  {get;}
        TextBox UsernameTextBox  {get;}
        StaticControl OrganizationStaticControl  {get;}
        TextBox OrganizationTextBox  {get;}
        TextBox Intheboxesbelowtypeyour25characterCDkeyYoullfindthisnumberontheyellowstickeronthebackoftheCDjewelcasTextBox  {get;}
        TextBox _TextBox  {get;}
        TextBox _TextBox2  {get;}
        TextBox _TextBox3  {get;}
        TextBox _TextBox4  {get;}
        Button NextButton  {get;}
        Button BackButton  {get;}
        Button CancelButton  {get;}
        StaticControl PleaseenteryournameandorganizationStaticControl  {get;}
        StaticControl Intheboxesbelowtypeyour25characterCDkeyYoullfindthisnumberontheyellowstickeronthebackoftheCDjewelcasStaticControl  {get;}
        StaticControl _StaticControl  {get;}
        StaticControl _StaticControl2  {get;}
        StaticControl _StaticControl3  {get;}
        StaticControl _StaticControl4  {get;}
    }
    
    /// -----------------------------------------------------------------------------
    /// Project		:  Maui
    // Class		: 
    ///  Copyright (C) 2002, oration
    /// -----------------------------------------------------------------------------
    ///  <summary>
    ///  TODO: Add dialog functionality description here.
    ///  </summary>
    ///  <remarks></remarks>
    ///  <history>[deangj] 4/10/2003 Created
    ///  </history>
    /// -----------------------------------------------------------------------------
    /// 
    public class MicrosoftOperationsManagerSetupRegistrationInformationDialog : Dialog, IMicrosoftOperationsManagerSetupRegistrationInformationDialogControls
    {
        protected StaticControl m_CachedUsernameStaticControl;
        protected TextBox m_CachedUsernameTextBox;
        protected StaticControl m_CachedOrganizationStaticControl;
        protected TextBox m_CachedOrganizationTextBox;
        protected TextBox m_CachedIntheboxesbelowtypeyour25characterCDkeyYoullfindthisnumberontheyellowstickeronthebackoftheCDjewelcasTextBox;
        protected TextBox m_Cached_TextBox;
        protected TextBox m_Cached_TextBox2;
        protected TextBox m_Cached_TextBox3;
        protected TextBox m_Cached_TextBox4;
        protected Button m_CachedNextButton;
        protected Button m_CachedBackButton;
        protected Button m_CachedCancelButton;
        protected StaticControl m_CachedPleaseenteryournameandorganizationStaticControl;
        protected StaticControl m_CachedIntheboxesbelowtypeyour25characterCDkeyYoullfindthisnumberontheyellowstickeronthebackoftheCDjewelcasStaticControl;
        protected StaticControl m_Cached_StaticControl;
        protected StaticControl m_Cached_StaticControl2;
        protected StaticControl m_Cached_StaticControl3;
        protected StaticControl m_Cached_StaticControl4;
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  TODO: Add a description for your constructor.
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Maker Tool] 4/10/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public MicrosoftOperationsManagerSetupRegistrationInformationDialog(App app) : 
                base(app, Init(app))
        {
            // TODO: Add Constructor logic here. 
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the raw controls for this dialog
        ///  </summary>
        ///  <value>An interface that groups all of the dialog's control properties together</value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual IMicrosoftOperationsManagerSetupRegistrationInformationDialogControls Controls
        {
            get
            {
                return this;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to set/get the text in control Username
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual string UsernameText
        {
            get
            {
                return Controls.UsernameTextBox.Text;
            }
            set
            {
                Controls.UsernameTextBox.Text = value;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to set/get the text in control Organization
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual string OrganizationText
        {
            get
            {
                return Controls.OrganizationTextBox.Text;
            }
            set
            {
                Controls.OrganizationTextBox.Text = value;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to set/get the text in control Intheboxesbelowtypeyour25characterCDkeyYoullfindthisnumberontheyellowstickeronthebackoftheCDjewelcas
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual string Intheboxesbelowtypeyour25characterCDkeyYoullfindthisnumberontheyellowstickeronthebackoftheCDjewelcasText
        {
            get
            {
                return Controls.Intheboxesbelowtypeyour25characterCDkeyYoullfindthisnumberontheyellowstickeronthebackoftheCDjewelcasTextBox.Text;
            }
            set
            {
                Controls.Intheboxesbelowtypeyour25characterCDkeyYoullfindthisnumberontheyellowstickeronthebackoftheCDjewelcasTextBox.Text = value;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to set/get the text in control _
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual string _Text
        {
            get
            {
                return Controls._TextBox.Text;
            }
            set
            {
                Controls._TextBox.Text = value;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to set/get the text in control _2
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual string _2Text
        {
            get
            {
                return Controls._TextBox2.Text;
            }
            set
            {
                Controls._TextBox2.Text = value;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to set/get the text in control _3
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual string _3Text
        {
            get
            {
                return Controls._TextBox3.Text;
            }
            set
            {
                Controls._TextBox3.Text = value;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to set/get the text in control _4
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual string _4Text
        {
            get
            {
                return Controls._TextBox4.Text;
            }
            set
            {
                Controls._TextBox4.Text = value;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the UsernameStaticControl control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        StaticControl IMicrosoftOperationsManagerSetupRegistrationInformationDialogControls.UsernameStaticControl
        {
            get
            {
                if ((m_CachedUsernameStaticControl == null))
                {
                    m_CachedUsernameStaticControl = new StaticControl(this, ControlIDs.UsernameStaticControl);
                }
                return m_CachedUsernameStaticControl;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the UsernameTextBox control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        TextBox IMicrosoftOperationsManagerSetupRegistrationInformationDialogControls.UsernameTextBox
        {
            get
            {
                if ((m_CachedUsernameTextBox == null))
                {
                    m_CachedUsernameTextBox = new TextBox(this, ControlIDs.UsernameTextBox);
                }
                return m_CachedUsernameTextBox;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the OrganizationStaticControl control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        StaticControl IMicrosoftOperationsManagerSetupRegistrationInformationDialogControls.OrganizationStaticControl
        {
            get
            {
                if ((m_CachedOrganizationStaticControl == null))
                {
                    m_CachedOrganizationStaticControl = new StaticControl(this, ControlIDs.OrganizationStaticControl);
                }
                return m_CachedOrganizationStaticControl;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the OrganizationTextBox control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        TextBox IMicrosoftOperationsManagerSetupRegistrationInformationDialogControls.OrganizationTextBox
        {
            get
            {
                if ((m_CachedOrganizationTextBox == null))
                {
                    m_CachedOrganizationTextBox = new TextBox(this, ControlIDs.OrganizationTextBox);
                }
                return m_CachedOrganizationTextBox;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the Intheboxesbelowtypeyour25characterCDkeyYoullfindthisnumberontheyellowstickeronthebackoftheCDjewelcasTextBox control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        TextBox IMicrosoftOperationsManagerSetupRegistrationInformationDialogControls.Intheboxesbelowtypeyour25characterCDkeyYoullfindthisnumberontheyellowstickeronthebackoftheCDjewelcasTextBox
        {
            get
            {
                if ((m_CachedIntheboxesbelowtypeyour25characterCDkeyYoullfindthisnumberontheyellowstickeronthebackoftheCDjewelcasTextBox == null))
                {
                    m_CachedIntheboxesbelowtypeyour25characterCDkeyYoullfindthisnumberontheyellowstickeronthebackoftheCDjewelcasTextBox = new TextBox(this, ControlIDs.Intheboxesbelowtypeyour25characterCDkeyYoullfindthisnumberontheyellowstickeronthebackoftheCDjewelcasTextBox);
                }
                return m_CachedIntheboxesbelowtypeyour25characterCDkeyYoullfindthisnumberontheyellowstickeronthebackoftheCDjewelcasTextBox;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the _TextBox control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        TextBox IMicrosoftOperationsManagerSetupRegistrationInformationDialogControls._TextBox
        {
            get
            {
                if ((m_Cached_TextBox == null))
                {
                    m_Cached_TextBox = new TextBox(this, ControlIDs._TextBox);
                }
                return m_Cached_TextBox;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the _TextBox2 control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        TextBox IMicrosoftOperationsManagerSetupRegistrationInformationDialogControls._TextBox2
        {
            get
            {
                if ((m_Cached_TextBox2 == null))
                {
                    m_Cached_TextBox2 = new TextBox(this, ControlIDs._TextBox2);
                }
                return m_Cached_TextBox2;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the _TextBox3 control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        TextBox IMicrosoftOperationsManagerSetupRegistrationInformationDialogControls._TextBox3
        {
            get
            {
                if ((m_Cached_TextBox3 == null))
                {
                    m_Cached_TextBox3 = new TextBox(this, ControlIDs._TextBox3);
                }
                return m_Cached_TextBox3;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the _TextBox4 control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        TextBox IMicrosoftOperationsManagerSetupRegistrationInformationDialogControls._TextBox4
        {
            get
            {
                if ((m_Cached_TextBox4 == null))
                {
                    m_Cached_TextBox4 = new TextBox(this, ControlIDs._TextBox4);
                }
                return m_Cached_TextBox4;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the NextButton control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        Button IMicrosoftOperationsManagerSetupRegistrationInformationDialogControls.NextButton
        {
            get
            {
                if ((m_CachedNextButton == null))
                {
                    m_CachedNextButton = new Button(this, ControlIDs.NextButton);
                }
                return m_CachedNextButton;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the BackButton control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        Button IMicrosoftOperationsManagerSetupRegistrationInformationDialogControls.BackButton
        {
            get
            {
                if ((m_CachedBackButton == null))
                {
                    m_CachedBackButton = new Button(this, ControlIDs.BackButton);
                }
                return m_CachedBackButton;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the CancelButton control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        Button IMicrosoftOperationsManagerSetupRegistrationInformationDialogControls.CancelButton
        {
            get
            {
                if ((m_CachedCancelButton == null))
                {
                    m_CachedCancelButton = new Button(this, ControlIDs.CancelButton);
                }
                return m_CachedCancelButton;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the PleaseenteryournameandorganizationStaticControl control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        StaticControl IMicrosoftOperationsManagerSetupRegistrationInformationDialogControls.PleaseenteryournameandorganizationStaticControl
        {
            get
            {
                if ((m_CachedPleaseenteryournameandorganizationStaticControl == null))
                {
                    m_CachedPleaseenteryournameandorganizationStaticControl = new StaticControl(this, ControlIDs.PleaseenteryournameandorganizationStaticControl);
                }
                return m_CachedPleaseenteryournameandorganizationStaticControl;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the Intheboxesbelowtypeyour25characterCDkeyYoullfindthisnumberontheyellowstickeronthebackoftheCDjewelcasStaticControl control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        StaticControl IMicrosoftOperationsManagerSetupRegistrationInformationDialogControls.Intheboxesbelowtypeyour25characterCDkeyYoullfindthisnumberontheyellowstickeronthebackoftheCDjewelcasStaticControl
        {
            get
            {
                if ((m_CachedIntheboxesbelowtypeyour25characterCDkeyYoullfindthisnumberontheyellowstickeronthebackoftheCDjewelcasStaticControl == null))
                {
                    m_CachedIntheboxesbelowtypeyour25characterCDkeyYoullfindthisnumberontheyellowstickeronthebackoftheCDjewelcasStaticControl = new StaticControl(this, ControlIDs.Intheboxesbelowtypeyour25characterCDkeyYoullfindthisnumberontheyellowstickeronthebackoftheCDjewelcasStaticControl);
                }
                return m_CachedIntheboxesbelowtypeyour25characterCDkeyYoullfindthisnumberontheyellowstickeronthebackoftheCDjewelcasStaticControl;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the _StaticControl control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        StaticControl IMicrosoftOperationsManagerSetupRegistrationInformationDialogControls._StaticControl
        {
            get
            {
                if ((m_Cached_StaticControl == null))
                {
                    m_Cached_StaticControl = new StaticControl(this, ControlIDs._StaticControl);
                }
                return m_Cached_StaticControl;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the _StaticControl2 control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        StaticControl IMicrosoftOperationsManagerSetupRegistrationInformationDialogControls._StaticControl2
        {
            get
            {
                if ((m_Cached_StaticControl2 == null))
                {
                    m_Cached_StaticControl2 = new StaticControl(this, ControlIDs._StaticControl2);
                }
                return m_Cached_StaticControl2;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the _StaticControl3 control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        StaticControl IMicrosoftOperationsManagerSetupRegistrationInformationDialogControls._StaticControl3
        {
            get
            {
                if ((m_Cached_StaticControl3 == null))
                {
                    m_Cached_StaticControl3 = new StaticControl(this, ControlIDs._StaticControl3);
                }
                return m_Cached_StaticControl3;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the _StaticControl4 control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        StaticControl IMicrosoftOperationsManagerSetupRegistrationInformationDialogControls._StaticControl4
        {
            get
            {
                if ((m_Cached_StaticControl4 == null))
                {
                    m_Cached_StaticControl4 = new StaticControl(this, ControlIDs._StaticControl4);
                }
                return m_Cached_StaticControl4;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  This function will attempt to find a showing instance of the dialog.
        ///  </summary>
        ///  <returns>The dialog's hWnd</returns>
        ///  <remarks></remarks>)
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        private static int Init(App app)
        {
            // First check if the dialog is already up.
            Window tempWindow = new Window(Strings.DialogTitle, "GLBSWizard", true, 0, app.Process.Id);
            if ((tempWindow != null))
            {
                return tempWindow.Extended.HWnd;
            }
            // Dialog not found.  Need to invoke the dialog.
            // TODO: Add code to bring up dthe dialog
            // 
            // TODO: Remove next line.  Your code should return the handle of the dialog.
            return 0;
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to click on button Next
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual void ClickNext()
        {
            Controls.NextButton.Click();
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to click on button Back
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual void ClickBack()
        {
            Controls.BackButton.Click();
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to click on button Cancel
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/10/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual void ClickCancel()
        {
            Controls.CancelButton.Click();
        }
        
        public class Strings
        {
            public const string DialogTitle = "Microsoft Operations Manager Setup - Registration Information";
            public const string Username = "&User name:";
            public const string Organization = "&Organization:";
            public const string Next = "&Next >";
            public const string Back = "< &Back";
            public const string Cancel = "Cancel";
            public const string Pleaseenteryournameandorganization = "Please enter your name and organization:";
            public const string Intheboxesbelowtypeyour25characterCDkeyYoullfindthisnumberontheyellowstickeronthebackoftheCDjewelcas = "In the boxes below, type your 25-character CD key. You\'ll find this number on the" +
" yellow sticker on the back of the CD jewel case. \r\n\r\n&Product key:";
            public const string _ = "_";
            public const string _2 = "_";
            public const string _3 = "_";
            public const string _4 = "_";
        }
        
        public class ControlIDs
        {
            public const int UsernameStaticControl = 3;
            public const int UsernameTextBox = 4;
            public const int OrganizationStaticControl = 5;
            public const int OrganizationTextBox = 6;
            public const int Intheboxesbelowtypeyour25characterCDkeyYoullfindthisnumberontheyellowstickeronthebackoftheCDjewelcasTextBox = 7;
            public const int _TextBox = 8;
            public const int _TextBox2 = 9;
            public const int _TextBox3 = 10;
            public const int _TextBox4 = 11;
            public const int NextButton = 12;
            public const int BackButton = 13;
            public const int CancelButton = 14;
            public const int PleaseenteryournameandorganizationStaticControl = 15;
            public const int Intheboxesbelowtypeyour25characterCDkeyYoullfindthisnumberontheyellowstickeronthebackoftheCDjewelcasStaticControl = 17;
            public const int _StaticControl = 18;
            public const int _StaticControl2 = 19;
            public const int _StaticControl3 = 20;
            public const int _StaticControl4 = 21;
        }
    }
}
