//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// ' For information on how interfaces are used in classes derived from Window,
// '   please see http://mauiweb.
namespace MOM10SP1_Install
{
    using System;
    using System.ComponentModel;
    using Maui.OS.WinControls;
    using Maui.OS;
    
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    public interface IMicrosoftOperationsManagerSetupInstallationTypeDialogControls
    {
        StaticControl TypeofinstallationStaticControl  {get;}
        Button NextButton  {get;}
        Button BackButton  {get;}
        Button CancelButton  {get;}
        RadioButton TypicalRadioButton  {get;}
        RadioButton UserInterfacesRadioButton  {get;}
        RadioButton CustomRadioButton  {get;}
        RadioButton ExpressRadioButton  {get;}
        TextBox NameASTestOperationsLabOrganizationMSProductIDQVG72JKDK4FR3Q8JKXGCFDG7MTextBox  {get;}
    }
    
    /// -----------------------------------------------------------------------------
    /// Project		:  Maui
    // Class		: 
    ///  Copyright (C) 2002, oration
    /// -----------------------------------------------------------------------------
    ///  <summary>
    ///  TODO: Add dialog functionality description here.
    ///  </summary>
    ///  <remarks></remarks>
    ///  <history>[deangj] 4/11/2003 Created
    ///  </history>
    /// -----------------------------------------------------------------------------
    /// 
    public class MicrosoftOperationsManagerSetupInstallationTypeDialog : Dialog, IMicrosoftOperationsManagerSetupInstallationTypeDialogControls
    {
        protected StaticControl m_CachedTypeofinstallationStaticControl;
        protected Button m_CachedNextButton;
        protected Button m_CachedBackButton;
        protected Button m_CachedCancelButton;
        protected RadioButton m_CachedTypicalRadioButton;
        protected RadioButton m_CachedUserInterfacesRadioButton;
        protected RadioButton m_CachedCustomRadioButton;
        protected RadioButton m_CachedExpressRadioButton;
        protected TextBox m_CachedNameASTestOperationsLabOrganizationMSProductIDQVG72JKDK4FR3Q8JKXGCFDG7MTextBox;
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  TODO: Add a description for your constructor.
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public MicrosoftOperationsManagerSetupInstallationTypeDialog(App app) : 
                base(app, Init(app))
        {
            // TODO: Add Constructor logic here. 
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the raw controls for this dialog
        ///  </summary>
        ///  <value>An interface that groups all of the dialog's control properties together</value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual IMicrosoftOperationsManagerSetupInstallationTypeDialogControls Controls
        {
            get
            {
                return this;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to set/get the text in control NameASTestOperationsLabOrganizationMSProductIDQVG72JKDK4FR3Q8JKXGCFDG7M
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual string NameASTestOperationsLabOrganizationMSProductIDQVG72JKDK4FR3Q8JKXGCFDG7MText
        {
            get
            {
                return Controls.NameASTestOperationsLabOrganizationMSProductIDQVG72JKDK4FR3Q8JKXGCFDG7MTextBox.Text;
            }
            set
            {
                Controls.NameASTestOperationsLabOrganizationMSProductIDQVG72JKDK4FR3Q8JKXGCFDG7MTextBox.Text = value;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the TypeofinstallationStaticControl control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        StaticControl IMicrosoftOperationsManagerSetupInstallationTypeDialogControls.TypeofinstallationStaticControl
        {
            get
            {
                if ((m_CachedTypeofinstallationStaticControl == null))
                {
                    m_CachedTypeofinstallationStaticControl = new StaticControl(this, ControlIDs.TypeofinstallationStaticControl);
                }
                return m_CachedTypeofinstallationStaticControl;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the NextButton control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        Button IMicrosoftOperationsManagerSetupInstallationTypeDialogControls.NextButton
        {
            get
            {
                if ((m_CachedNextButton == null))
                {
                    m_CachedNextButton = new Button(this, ControlIDs.NextButton);
                }
                return m_CachedNextButton;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the BackButton control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        Button IMicrosoftOperationsManagerSetupInstallationTypeDialogControls.BackButton
        {
            get
            {
                if ((m_CachedBackButton == null))
                {
                    m_CachedBackButton = new Button(this, ControlIDs.BackButton);
                }
                return m_CachedBackButton;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the CancelButton control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        Button IMicrosoftOperationsManagerSetupInstallationTypeDialogControls.CancelButton
        {
            get
            {
                if ((m_CachedCancelButton == null))
                {
                    m_CachedCancelButton = new Button(this, ControlIDs.CancelButton);
                }
                return m_CachedCancelButton;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the TypicalRadioButton control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        RadioButton IMicrosoftOperationsManagerSetupInstallationTypeDialogControls.TypicalRadioButton
        {
            get
            {
                if ((m_CachedTypicalRadioButton == null))
                {
                    m_CachedTypicalRadioButton = new RadioButton(this, ControlIDs.TypicalRadioButton);
                }
                return m_CachedTypicalRadioButton;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the UserInterfacesRadioButton control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        RadioButton IMicrosoftOperationsManagerSetupInstallationTypeDialogControls.UserInterfacesRadioButton
        {
            get
            {
                if ((m_CachedUserInterfacesRadioButton == null))
                {
                    m_CachedUserInterfacesRadioButton = new RadioButton(this, ControlIDs.UserInterfacesRadioButton);
                }
                return m_CachedUserInterfacesRadioButton;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the CustomRadioButton control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        RadioButton IMicrosoftOperationsManagerSetupInstallationTypeDialogControls.CustomRadioButton
        {
            get
            {
                if ((m_CachedCustomRadioButton == null))
                {
                    m_CachedCustomRadioButton = new RadioButton(this, ControlIDs.CustomRadioButton);
                }
                return m_CachedCustomRadioButton;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the ExpressRadioButton control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        RadioButton IMicrosoftOperationsManagerSetupInstallationTypeDialogControls.ExpressRadioButton
        {
            get
            {
                if ((m_CachedExpressRadioButton == null))
                {
                    m_CachedExpressRadioButton = new RadioButton(this, ControlIDs.ExpressRadioButton);
                }
                return m_CachedExpressRadioButton;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the NameASTestOperationsLabOrganizationMSProductIDQVG72JKDK4FR3Q8JKXGCFDG7MTextBox control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        TextBox IMicrosoftOperationsManagerSetupInstallationTypeDialogControls.NameASTestOperationsLabOrganizationMSProductIDQVG72JKDK4FR3Q8JKXGCFDG7MTextBox
        {
            get
            {
                if ((m_CachedNameASTestOperationsLabOrganizationMSProductIDQVG72JKDK4FR3Q8JKXGCFDG7MTextBox == null))
                {
                    m_CachedNameASTestOperationsLabOrganizationMSProductIDQVG72JKDK4FR3Q8JKXGCFDG7MTextBox = new TextBox(this, ControlIDs.NameASTestOperationsLabOrganizationMSProductIDQVG72JKDK4FR3Q8JKXGCFDG7MTextBox);
                }
                return m_CachedNameASTestOperationsLabOrganizationMSProductIDQVG72JKDK4FR3Q8JKXGCFDG7MTextBox;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  This function will attempt to find a showing instance of the dialog.
        ///  </summary>
        ///  <returns>The dialog's hWnd</returns>
        ///  <remarks></remarks>)
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        private static int Init(App app)
        {
            // First check if the dialog is already up.
            Window tempWindow = new Window(Strings.DialogTitle, "GLBSWizard", true, 0, app.Process.Id);
            if ((tempWindow != null))
            {
                return tempWindow.Extended.HWnd;
            }
            // Dialog not found.  Need to invoke the dialog.
            // TODO: Add code to bring up dthe dialog
            // 
            // TODO: Remove next line.  Your code should return the handle of the dialog.
            return 0;
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to click on button Next
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual void ClickNext()
        {
            Controls.NextButton.Click();
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to click on button Back
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual void ClickBack()
        {
            Controls.BackButton.Click();
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to click on button Cancel
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual void ClickCancel()
        {
            Controls.CancelButton.Click();
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to click on button Typical
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual void ClickTypical()
        {
            Controls.TypicalRadioButton.Click();
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to click on button UserInterfaces
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual void ClickUserInterfaces()
        {
            Controls.UserInterfacesRadioButton.Click();
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to click on button Custom
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual void ClickCustom()
        {
            Controls.CustomRadioButton.Click();
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to click on button Express
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual void ClickExpress()
        {
            Controls.ExpressRadioButton.Click();
        }
        
        public class Strings
        {
            public const string DialogTitle = "Microsoft Operations Manager Setup - Installation Type";
            public const string Typeofinstallation = "Type of installation:";
            public const string Next = "&Next >";
            public const string Back = "< &Back";
            public const string Cancel = "Cancel";
            public const string Typical = "&Typical";
            public const string UserInterfaces = "&User Interfaces";
            public const string Custom = "&Custom";
            public const string Express = "&Express";
        }
        
        public class ControlIDs
        {
            public const int TypeofinstallationStaticControl = 3;
            public const int NextButton = 4;
            public const int BackButton = 5;
            public const int CancelButton = 6;
            public const int TypicalRadioButton = 8;
            public const int UserInterfacesRadioButton = 9;
            public const int CustomRadioButton = 10;
            public const int ExpressRadioButton = 11;
            public const int NameASTestOperationsLabOrganizationMSProductIDQVG72JKDK4FR3Q8JKXGCFDG7MTextBox = 12;
        }
    }
}
