//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// ' For information on how interfaces are used in classes derived from Window,
// '   please see http://mauiweb.
namespace MOM10SP1_Install
{
    using System;
    using System.ComponentModel;
    using Maui.OS.WinControls;
    using Maui.OS;
    
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    public interface IMicrosoftOperationsManagerSetupDatabaseInstanceDialogControls
    {
        Button NextButton  {get;}
        Button BackButton  {get;}
        Button CancelButton  {get;}
        StaticControl YouhaveselectedtoinstallMicrosoftOperationsManagerdatabaseSelectthenameoftheSQLServerinstancetohosttStaticControl  {get;}
        StaticControl ServernameStaticControl  {get;}
        EditComboBox ServernameEditComboBox  {get;}
    }
    
    /// -----------------------------------------------------------------------------
    /// Project		:  Maui
    // Class		: 
    ///  Copyright (C) 2002, oration
    /// -----------------------------------------------------------------------------
    ///  <summary>
    ///  TODO: Add dialog functionality description here.
    ///  </summary>
    ///  <remarks></remarks>
    ///  <history>[deangj] 4/11/2003 Created
    ///  </history>
    /// -----------------------------------------------------------------------------
    /// 
    public class MicrosoftOperationsManagerSetupDatabaseInstanceDialog : Dialog, IMicrosoftOperationsManagerSetupDatabaseInstanceDialogControls
    {
        protected Button m_CachedNextButton;
        protected Button m_CachedBackButton;
        protected Button m_CachedCancelButton;
        protected StaticControl m_CachedYouhaveselectedtoinstallMicrosoftOperationsManagerdatabaseSelectthenameoftheSQLServerinstancetohosttStaticControl;
        protected StaticControl m_CachedServernameStaticControl;
        protected EditComboBox m_CachedServernameEditComboBox;
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  TODO: Add a description for your constructor.
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public MicrosoftOperationsManagerSetupDatabaseInstanceDialog(App app) : 
                base(app, Init(app))
        {
            // TODO: Add Constructor logic here. 
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the raw controls for this dialog
        ///  </summary>
        ///  <value>An interface that groups all of the dialog's control properties together</value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual IMicrosoftOperationsManagerSetupDatabaseInstanceDialogControls Controls
        {
            get
            {
                return this;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to set/get the text in control Servername
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual string ServernameText
        {
            get
            {
                return Controls.ServernameEditComboBox.Text;
            }
            set
            {
                Controls.ServernameEditComboBox.Text = value;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the NextButton control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        Button IMicrosoftOperationsManagerSetupDatabaseInstanceDialogControls.NextButton
        {
            get
            {
                if ((m_CachedNextButton == null))
                {
                    m_CachedNextButton = new Button(this, ControlIDs.NextButton);
                }
                return m_CachedNextButton;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the BackButton control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        Button IMicrosoftOperationsManagerSetupDatabaseInstanceDialogControls.BackButton
        {
            get
            {
                if ((m_CachedBackButton == null))
                {
                    m_CachedBackButton = new Button(this, ControlIDs.BackButton);
                }
                return m_CachedBackButton;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the CancelButton control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        Button IMicrosoftOperationsManagerSetupDatabaseInstanceDialogControls.CancelButton
        {
            get
            {
                if ((m_CachedCancelButton == null))
                {
                    m_CachedCancelButton = new Button(this, ControlIDs.CancelButton);
                }
                return m_CachedCancelButton;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the YouhaveselectedtoinstallMicrosoftOperationsManagerdatabaseSelectthenameoftheSQLServerinstancetohosttStaticControl control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        StaticControl IMicrosoftOperationsManagerSetupDatabaseInstanceDialogControls.YouhaveselectedtoinstallMicrosoftOperationsManagerdatabaseSelectthenameoftheSQLServerinstancetohosttStaticControl
        {
            get
            {
                if ((m_CachedYouhaveselectedtoinstallMicrosoftOperationsManagerdatabaseSelectthenameoftheSQLServerinstancetohosttStaticControl == null))
                {
                    m_CachedYouhaveselectedtoinstallMicrosoftOperationsManagerdatabaseSelectthenameoftheSQLServerinstancetohosttStaticControl = new StaticControl(this, ControlIDs.YouhaveselectedtoinstallMicrosoftOperationsManagerdatabaseSelectthenameoftheSQLServerinstancetohosttStaticControl);
                }
                return m_CachedYouhaveselectedtoinstallMicrosoftOperationsManagerdatabaseSelectthenameoftheSQLServerinstancetohosttStaticControl;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the ServernameStaticControl control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        StaticControl IMicrosoftOperationsManagerSetupDatabaseInstanceDialogControls.ServernameStaticControl
        {
            get
            {
                if ((m_CachedServernameStaticControl == null))
                {
                    m_CachedServernameStaticControl = new StaticControl(this, ControlIDs.ServernameStaticControl);
                }
                return m_CachedServernameStaticControl;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the ServernameEditComboBox control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        EditComboBox IMicrosoftOperationsManagerSetupDatabaseInstanceDialogControls.ServernameEditComboBox
        {
            get
            {
                if ((m_CachedServernameEditComboBox == null))
                {
                    m_CachedServernameEditComboBox = new EditComboBox(this, ControlIDs.ServernameEditComboBox);
                }
                return m_CachedServernameEditComboBox;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  This function will attempt to find a showing instance of the dialog.
        ///  </summary>
        ///  <returns>The dialog's hWnd</returns>
        ///  <remarks></remarks>)
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        private static int Init(App app)
        {
            // First check if the dialog is already up.
            Window tempWindow = new Window(Strings.DialogTitle, Constants.WinClass., true, 0, app.Process.Id);
            if ((tempWindow != null))
            {
                return tempWindow.Extended.HWnd;
            }
            // Dialog not found.  Need to invoke the dialog.
            // TODO: Add code to bring up dthe dialog
            // 
            // TODO: Remove next line.  Your code should return the handle of the dialog.
            return 0;
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to click on button Next
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual void ClickNext()
        {
            Controls.NextButton.Click();
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to click on button Back
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual void ClickBack()
        {
            Controls.BackButton.Click();
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to click on button Cancel
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual void ClickCancel()
        {
            Controls.CancelButton.Click();
        }
        
        public class Strings
        {
            public const string DialogTitle = "Microsoft Operations Manager Setup - Database Instance";
            public const string Next = "&Next >";
            public const string Back = "< &Back";
            public const string Cancel = "Cancel";
            public const string YouhaveselectedtoinstallMicrosoftOperationsManagerdatabaseSelectthenameoftheSQLServerinstancetohostt = "You have selected to install Microsoft Operations Manager database. \r\n\r\nSelect th" +
"e name of the SQL Server instance to host the Microsoft Operations Manager 2000 " +
"database.";
            public const string Servername = "&Server name:";
        }
        
        public class ControlIDs
        {
            public const int NextButton = 3;
            public const int BackButton = 4;
            public const int CancelButton = 5;
            public const int YouhaveselectedtoinstallMicrosoftOperationsManagerdatabaseSelectthenameoftheSQLServerinstancetohosttStaticControl = 7;
            public const int ServernameStaticControl = 8;
            public const int ServernameEditComboBox = 9;
        }
    }
}
