//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// ' For information on how interfaces are used in classes derived from Window,
// '   please see http://mauiweb.
namespace MOM10SP1_Install
{
    using System;
    using System.ComponentModel;
    using Maui.OS.WinControls;
    using Maui.OS;
    
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    public interface IMicrosoftOperationsManagerSetupDASAccountInformationDialogControls
    {
        StaticControl AccountStaticControl  {get;}
        TextBox AccountTextBox  {get;}
        StaticControl PasswordStaticControl  {get;}
        TextBox PasswordTextBox  {get;}
        StaticControl DomainorLocalComputerStaticControl  {get;}
        TextBox DomainorLocalComputerTextBox  {get;}
        CheckBox UsethisaccountforConsolidatorAgentManagercomponentCheckBox  {get;}
        Button NextButton  {get;}
        Button BackButton  {get;}
        Button CancelButton  {get;}
        StaticControl TheDataAccessServerDASprovidescentralizeddatabaseaccesslogicTheDAScomputermustlogonusinganaccountwitStaticControl  {get;}
    }
    
    /// -----------------------------------------------------------------------------
    /// Project		:  Maui
    // Class		: 
    ///  Copyright (C) 2002, oration
    /// -----------------------------------------------------------------------------
    ///  <summary>
    ///  TODO: Add dialog functionality description here.
    ///  </summary>
    ///  <remarks></remarks>
    ///  <history>[deangj] 4/11/2003 Created
    ///  </history>
    /// -----------------------------------------------------------------------------
    /// 
    public class MicrosoftOperationsManagerSetupDASAccountInformationDialog : Dialog, IMicrosoftOperationsManagerSetupDASAccountInformationDialogControls
    {
        protected StaticControl m_CachedAccountStaticControl;
        protected TextBox m_CachedAccountTextBox;
        protected StaticControl m_CachedPasswordStaticControl;
        protected TextBox m_CachedPasswordTextBox;
        protected StaticControl m_CachedDomainorLocalComputerStaticControl;
        protected TextBox m_CachedDomainorLocalComputerTextBox;
        protected CheckBox m_CachedUsethisaccountforConsolidatorAgentManagercomponentCheckBox;
        protected Button m_CachedNextButton;
        protected Button m_CachedBackButton;
        protected Button m_CachedCancelButton;
        protected StaticControl m_CachedTheDataAccessServerDASprovidescentralizeddatabaseaccesslogicTheDAScomputermustlogonusinganaccountwitStaticControl;
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  TODO: Add a description for your constructor.
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public MicrosoftOperationsManagerSetupDASAccountInformationDialog(App app) : 
                base(app, Init(app))
        {
            // TODO: Add Constructor logic here. 
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the raw controls for this dialog
        ///  </summary>
        ///  <value>An interface that groups all of the dialog's control properties together</value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual IMicrosoftOperationsManagerSetupDASAccountInformationDialogControls Controls
        {
            get
            {
                return this;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to set/get the text in control Account
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual string AccountText
        {
            get
            {
                return Controls.AccountTextBox.Text;
            }
            set
            {
                Controls.AccountTextBox.Text = value;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to set/get the text in control Password
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual string PasswordText
        {
            get
            {
                return Controls.PasswordTextBox.Text;
            }
            set
            {
                Controls.PasswordTextBox.Text = value;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to set/get the text in control DomainorLocalComputer
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual string DomainorLocalComputerText
        {
            get
            {
                return Controls.DomainorLocalComputerTextBox.Text;
            }
            set
            {
                Controls.DomainorLocalComputerTextBox.Text = value;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the AccountStaticControl control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        StaticControl IMicrosoftOperationsManagerSetupDASAccountInformationDialogControls.AccountStaticControl
        {
            get
            {
                if ((m_CachedAccountStaticControl == null))
                {
                    m_CachedAccountStaticControl = new StaticControl(this, ControlIDs.AccountStaticControl);
                }
                return m_CachedAccountStaticControl;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the AccountTextBox control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        TextBox IMicrosoftOperationsManagerSetupDASAccountInformationDialogControls.AccountTextBox
        {
            get
            {
                if ((m_CachedAccountTextBox == null))
                {
                    m_CachedAccountTextBox = new TextBox(this, ControlIDs.AccountTextBox);
                }
                return m_CachedAccountTextBox;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the PasswordStaticControl control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        StaticControl IMicrosoftOperationsManagerSetupDASAccountInformationDialogControls.PasswordStaticControl
        {
            get
            {
                if ((m_CachedPasswordStaticControl == null))
                {
                    m_CachedPasswordStaticControl = new StaticControl(this, ControlIDs.PasswordStaticControl);
                }
                return m_CachedPasswordStaticControl;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the PasswordTextBox control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        TextBox IMicrosoftOperationsManagerSetupDASAccountInformationDialogControls.PasswordTextBox
        {
            get
            {
                if ((m_CachedPasswordTextBox == null))
                {
                    m_CachedPasswordTextBox = new TextBox(this, ControlIDs.PasswordTextBox);
                }
                return m_CachedPasswordTextBox;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the DomainorLocalComputerStaticControl control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        StaticControl IMicrosoftOperationsManagerSetupDASAccountInformationDialogControls.DomainorLocalComputerStaticControl
        {
            get
            {
                if ((m_CachedDomainorLocalComputerStaticControl == null))
                {
                    m_CachedDomainorLocalComputerStaticControl = new StaticControl(this, ControlIDs.DomainorLocalComputerStaticControl);
                }
                return m_CachedDomainorLocalComputerStaticControl;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the DomainorLocalComputerTextBox control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        TextBox IMicrosoftOperationsManagerSetupDASAccountInformationDialogControls.DomainorLocalComputerTextBox
        {
            get
            {
                if ((m_CachedDomainorLocalComputerTextBox == null))
                {
                    m_CachedDomainorLocalComputerTextBox = new TextBox(this, ControlIDs.DomainorLocalComputerTextBox);
                }
                return m_CachedDomainorLocalComputerTextBox;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the UsethisaccountforConsolidatorAgentManagercomponentCheckBox control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        CheckBox IMicrosoftOperationsManagerSetupDASAccountInformationDialogControls.UsethisaccountforConsolidatorAgentManagercomponentCheckBox
        {
            get
            {
                if ((m_CachedUsethisaccountforConsolidatorAgentManagercomponentCheckBox == null))
                {
                    m_CachedUsethisaccountforConsolidatorAgentManagercomponentCheckBox = new CheckBox(this, ControlIDs.UsethisaccountforConsolidatorAgentManagercomponentCheckBox);
                }
                return m_CachedUsethisaccountforConsolidatorAgentManagercomponentCheckBox;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the NextButton control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        Button IMicrosoftOperationsManagerSetupDASAccountInformationDialogControls.NextButton
        {
            get
            {
                if ((m_CachedNextButton == null))
                {
                    m_CachedNextButton = new Button(this, ControlIDs.NextButton);
                }
                return m_CachedNextButton;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the BackButton control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        Button IMicrosoftOperationsManagerSetupDASAccountInformationDialogControls.BackButton
        {
            get
            {
                if ((m_CachedBackButton == null))
                {
                    m_CachedBackButton = new Button(this, ControlIDs.BackButton);
                }
                return m_CachedBackButton;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the CancelButton control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        Button IMicrosoftOperationsManagerSetupDASAccountInformationDialogControls.CancelButton
        {
            get
            {
                if ((m_CachedCancelButton == null))
                {
                    m_CachedCancelButton = new Button(this, ControlIDs.CancelButton);
                }
                return m_CachedCancelButton;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Exposes access to the TheDataAccessServerDASprovidescentralizeddatabaseaccesslogicTheDAScomputermustlogonusinganaccountwitStaticControl control
        ///  </summary>
        ///  <value></value>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 - Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        StaticControl IMicrosoftOperationsManagerSetupDASAccountInformationDialogControls.TheDataAccessServerDASprovidescentralizeddatabaseaccesslogicTheDAScomputermustlogonusinganaccountwitStaticControl
        {
            get
            {
                if ((m_CachedTheDataAccessServerDASprovidescentralizeddatabaseaccesslogicTheDAScomputermustlogonusinganaccountwitStaticControl == null))
                {
                    m_CachedTheDataAccessServerDASprovidescentralizeddatabaseaccesslogicTheDAScomputermustlogonusinganaccountwitStaticControl = new StaticControl(this, ControlIDs.TheDataAccessServerDASprovidescentralizeddatabaseaccesslogicTheDAScomputermustlogonusinganaccountwitStaticControl);
                }
                return m_CachedTheDataAccessServerDASprovidescentralizeddatabaseaccesslogicTheDAScomputermustlogonusinganaccountwitStaticControl;
            }
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  This function will attempt to find a showing instance of the dialog.
        ///  </summary>
        ///  <returns>The dialog's hWnd</returns>
        ///  <remarks></remarks>)
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        private static int Init(App app)
        {
            // First check if the dialog is already up.
            Window tempWindow = new Window(Strings.DialogTitle, Constants.WinClass., true, 0, app.Process.Id);
            if ((tempWindow != null))
            {
                return tempWindow.Extended.HWnd;
            }
            // Dialog not found.  Need to invoke the dialog.
            // TODO: Add code to bring up dthe dialog
            // 
            // TODO: Remove next line.  Your code should return the handle of the dialog.
            return 0;
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to click on button UsethisaccountforConsolidatorAgentManagercomponent
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual void ClickUsethisaccountforConsolidatorAgentManagercomponent()
        {
            Controls.UsethisaccountforConsolidatorAgentManagercomponentCheckBox.Click();
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to click on button Next
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual void ClickNext()
        {
            Controls.NextButton.Click();
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to click on button Back
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual void ClickBack()
        {
            Controls.BackButton.Click();
        }
        
        /// -----------------------------------------------------------------------------
        ///  <summary>
        ///  Routine to click on button Cancel
        ///  </summary>
        ///  <remarks></remarks>
        ///  <history>[Dialog Class Maker Tool] 4/11/2003 Created
        ///  </history>
        /// -----------------------------------------------------------------------------
        public virtual void ClickCancel()
        {
            Controls.CancelButton.Click();
        }
        
        public class Strings
        {
            public const string DialogTitle = "Microsoft Operations Manager Setup - DAS Account Information";
            public const string Account = "&Account:";
            public const string Password = "&Password:";
            public const string DomainorLocalComputer = "&Domain or Local Computer:";
            public const string UsethisaccountforConsolidatorAgentManagercomponent = "&Use this account for Consolidator/Agent Manager component";
            public const string Next = "&Next >";
            public const string Back = "< &Back";
            public const string Cancel = "Cancel";
            public const string TheDataAccessServerDASprovidescentralizeddatabaseaccesslogicTheDAScomputermustlogonusinganaccountwit = "The Data Access Server (DAS) provides centralized database access logic. The DAS " +
"computer must log on using an account with Administrator privileges both on the " +
"DAS and on the computer containing the database. \r\n\r\nIf you want to use this acc" +
"ount for the C";
        }
        
        public class ControlIDs
        {
            public const int AccountStaticControl = 3;
            public const int AccountTextBox = 4;
            public const int PasswordStaticControl = 5;
            public const int PasswordTextBox = 6;
            public const int DomainorLocalComputerStaticControl = 7;
            public const int DomainorLocalComputerTextBox = 8;
            public const int UsethisaccountforConsolidatorAgentManagercomponentCheckBox = 9;
            public const int NextButton = 10;
            public const int BackButton = 11;
            public const int CancelButton = 12;
            public const int TheDataAccessServerDASprovidescentralizeddatabaseaccesslogicTheDAScomputermustlogonusinganaccountwitStaticControl = 14;
        }
    }
}
